general:
  debug: false
  instance_name: "SearXNG (Clio)"
  donation_url: false
  contact_url: false
  privacypolicy_url: false
  enable_metrics: false

brand: {}

search:
  safe_search: 1
  autocomplete: ""
  favicon_resolver: ""
  default_lang: "en-US"
  formats:
    - html
    - json

server:
  method: "GET"
  limiter: false
  public_instance: false

ui:
  default_theme: simple
  query_in_title: false
  center_alignment: false
  default_locale: ""
  theme_args:
    simple_style: auto

outgoing:
  request_timeout: 4.0
  enable_http2: true
  useragent_suffix: ""

plugins:
  searx.plugins.hash_plugin.SXNGPlugin:
    active: true
  searx.plugins.self_info.SXNGPlugin:
    active: true
  searx.plugins.tracker_url_remover.SXNGPlugin:
    active: true

doi_resolvers:
  oadoi.org: 'https://oadoi.org/'
  doi.org: 'https://doi.org/'

default_doi_resolver: 'oadoi.org'

engines:
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    display_type: ["infobox"]
    categories: [general]

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    categories: [general]
    weight: 1

  - name: bing
    engine: bing
    shortcut: bi
    categories: [general]
    weight: 1

  - name: duckduckgo news
    engine: duckduckgo_extra
    categories: [news]
    ddg_category: news
    shortcut: ddn
    weight: 1

  - name: bing news
    engine: bing_news
    categories: [news]
    shortcut: bin
    weight: 1

  - name: duckduckgo images
    engine: duckduckgo_extra
    categories: [images]
    ddg_category: images
    shortcut: ddi

  - name: duckduckgo videos
    engine: duckduckgo_extra
    categories: [videos]
    ddg_category: videos
    shortcut: ddv

  - name: github
    engine: github
    shortcut: gh
    categories: [it, repos]

  - name: pypi
    shortcut: pypi
    engine: pypi
    categories: [it, packages]

  - name: docker hub
    engine: docker_hub
    shortcut: dh
    categories: [it, packages]

  - name: npm
    engine: npm
    shortcut: npm
    timeout: 5.0
    categories: [it, packages]
    timeout: 5.0
    categories: [it, packages]
